[package]
name = "allen_crud"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["blocking"] }
rusqlite = { version = "0.31", features = ["bundled"] }
csv = "1.2"

[dev-dependencies]
assert_cmd = "2.0"